name: Base64 Converter

on:
  push:
    branches: [ main ]

  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Convert to base64
      run: |
          content=$(cat output/converted.txt | base64)
            echo "$content" > base64/converted.txt
          for file in output/US.txt output/IR.txt; do
            base64 $file > "base64/$(basename $file)"
          done
       
    - name: Check for Base64 Changes
      id: changes64
      run: |
            git diff --quiet && echo 'No changes' || echo '::set-output name=changed::true'   
      
    - name: Commit and push Base64
      if: steps.changes.outputs.changed == 'true'   
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add base64/converted.txt
          git add base64/*
          git commit --allow-empty -m "Update output files"
          git push
