name: Fetch proxies, Run python sorter and Base64

on:
  push:
    branches: [ main ]

  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run sorter
      run: python python/bugfix.py
    
    #- name: Check for Output Changes
     # id: changes
      #run: |
       # git diff --quiet && echo 'No changes' || echo '::set-output name=changed::true'   
      
    - name: Commit and push sorter changes
      #if: steps.changes.outputs.changed == 'true'   
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add output/bugfix.txt
        git commit -m "Update files" -a
        git push
