name: Ping Configs

on:
  push:
    paths:
      - '.github/workflows/xrayping.yml'
      - 'xray/xrayping.py'
      - 'xray/configs/all_configs.txt'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r xray/requirements.txt

    - name: Run sorter script
      run: python xray/xrayping.py
      
    - name: Check for Output Changes
      id: xrays
      run: |
        git diff --quiet && echo 'No changes' || echo '::set-output name=changed::true'   
      
    - name: Commit and push sorter changes
      if: steps.xrays.outputs.changed == 'true'   
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add xray/configs/actives_under_1000ms.txt xray/configs/actives_under_1500ms.txt xray/configs/actives_no_403_under_1000ms.txt
        git commit -m "Update files" -a
        git push
